echo -e '\e[40m\e[92m'
echo -e '                                      '
echo -e '     _____                            '
echo -e ' ___|   _ |__  _____  ____    __   _  '
echo -e '|    \ | |   |/     \|    \  |  |_| | '
echo -e '|     \| |   ||     ||     \ |   _  | '
echo -e '|__/\____| __|\_____/|__|\__\|__| |_| '
echo -e '    |_____|              Hoang Nguyen '
echo -e '                                      '
echo -e '\e[0m'
